#!/usr/bin/env python3

import os
from pathlib import Path
from cocotb_tools.runner import get_runner

def test_skew_buffer():
    """Simulate the skew buffer using the Python runner."""
    
    sim = os.getenv("SIM", "icarus") # Default to Icarus Verilog
    proj_path = Path(__file__).resolve().parent

    # 1. Build the simulation
    # This compiles your Verilog code
    runner = get_runner(sim)
    runner.build(
        sources=[proj_path / "test.v"],
        hdl_toplevel="top",
        build_dir=proj_path / "sim_build",

        timescale=('1ns', '1ps')
    )

    # 2. Run the test
    # This executes the @cocotb.test() function in your test_skew.py
    runner.test(
        hdl_toplevel="top",
        test_module="skewBufTest", 
        waves=True            
    )

if __name__ == "__main__":
    test_skew_buffer()